### ISSUE TITLE
关于react-seed webpack中commonschunkplugin 好像配置错误

### ISSUE THREAD

**Issue by meooxx** [JasonBai007/react-seed#2]

**Comment by meooxx** [comment]
是在reactSPA

**Comment by JasonBai007** [comment]
webpack2.x版本的配置不一样，我的那个项目用的是1.x的配置

**Comment by meooxx** [comment]
是的，我用的都是别人陪好的脚手架，想跟你这个项目多学习学习。报错就懵逼了。然后能不能让我做个伸手党，有比较好的项目，给我练习练习。。。感激不尽。发自网易邮箱大师
            在2017年03月11日 20:24，Bai Yanyun 写道： webpack2.x版本的配置不一样，我的那个项目用的是1.x的配置

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JasonBai007/react-seed","title":"JasonBai007/react-seed","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JasonBai007/react-seed"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JasonBai007 in #2: webpack2.x版本的配置不一样，我的那个项目用的是1.x的配置"}],"action":{"name":"View Issue","url":"https://github.com/JasonBai007/react-seed/issues/2#issuecomment-285863528"}}}
